import type { NextApiRequest, NextApiResponse } from "next";
import { supabaseAdmin } from "~supabase/admin";
import { requireAdmin } from "~lib/admin-auth";

/**
 * POST /api/admin/sample-essays/[id]/clone
 *
 * Deep-copy an existing sample essay into a new draft row. The copy keeps
 * every authored field (content, skill, part, question_type, topic, task,
 * passage, etc.) but resets identifiers, counters, and visibility:
 *   - id / created_at / published_at: regenerated by the DB
 *   - title: appended with " (Copy)"
 *   - slug: suffixed with -copy-<ms> for uniqueness
 *   - status: forced back to "draft" so the admin can review before
 *     re-publishing
 *   - views / votes: reset so the clone doesn't inherit the original's
 *     popularity counters
 */
export default async function handler(req: NextApiRequest, res: NextApiResponse) {
    if (req.method !== "POST") {
        return res.status(405).json({ success: false, error: "Method not allowed" });
    }

    const user = await requireAdmin(req, res);
    if (!user) return;

    const { id } = req.query;
    if (!id || typeof id !== "string") {
        return res.status(400).json({ success: false, error: "Missing sample essay ID" });
    }

    try {
        const { data: original, error } = await supabaseAdmin
            .from("sample_essays")
            .select("*")
            .eq("id", id)
            .single();

        if (error) throw error;
        if (!original) return res.status(404).json({ success: false, error: "Sample essay not found" });

        const {
            id: _origId,
            created_at: _origCreated,
            published_at: _origPublished,
            views: _origViews,
            votes: _origVotes,
            ...rest
        } = original;

        const insertPayload = {
            ...rest,
            title: `${original.title} (Copy)`,
            slug: `${original.slug}-copy-${Date.now()}`,
            status: "draft",
            published_at: null,
            views: 0,
            votes: [],
        };

        const { data: cloned, error: insertError } = await supabaseAdmin
            .from("sample_essays")
            .insert(insertPayload)
            .select()
            .single();

        if (insertError) throw insertError;

        return res.status(200).json({ success: true, data: cloned });
    } catch (error) {
        const pgErr = error as { code?: string };
        if (pgErr?.code === "PGRST116") {
            return res.status(404).json({ success: false, error: "Sample essay not found" });
        }
        console.error(`[API /api/admin/sample-essays/${id}/clone]`, error);
        return res.status(500).json({
            success: false,
            error: error instanceof Error ? error.message : "Internal error",
        });
    }
}
